name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Set up TinyGo
        uses: acifani/setup-tinygo@v2.0.0
        with:
          tinygo-version: "0.30.0"

      - name: Set up Wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1.0.0
        with:
          version: "v14.0.4"

      - name: Set up wasm-tools
        uses: bytecodealliance/actions/wasm-tools/setup@v1.0.0

      - name: Vet Go code
        run: go vet ./...

      - name: Test Go code
        run: go test -v -race ./...

      - name: Test Go without cgo
        env:
          CGO_ENABLED: 0
        run: go test -v ./...

      - name: Test with TinyGo
        run: tinygo test -v ./...

      - name: Test with TinyGo + WASI
        env:
          GOOS: wasip1
          GOARCH: wasm
        run: tinygo test -stack-size=64KB ./...

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD
